AWSTemplateFormatVersion: "2010-09-09"
Description: "Fireblocks Callback Handler - Security Stack (Security Groups, IAM, VPC Endpoints)"

Parameters:
  ProjectName:
    Type: String
    Default: fireblocks-cbh
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prod]
    Description: Environment name

Resources:
  # Cosigner用セキュリティグループ
  CosignerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Cosigner (Nitro Enclave)
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      SecurityGroupEgress:
        # ALBへのHTTPS通信
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationSecurityGroupId: !Ref ALBSecurityGroup
          Description: "HTTPS to ALB"
        # VPCエンドポイントへの通信
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationSecurityGroupId: !Ref VPCEndpointSecurityGroup
          Description: "HTTPS to VPC Endpoints"
        # Fireblocks SaaS API通信（NAT Gateway経由）
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: "HTTPS to Fireblocks SaaS API"
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-cosigner-sg-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: security
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # ALB用セキュリティグループ
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Application Load Balancer
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref CosignerSecurityGroup
          Description: "HTTPS from Cosigner"
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          DestinationSecurityGroupId: !Ref ECSSecurityGroup
          Description: "HTTP to ECS"
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-alb-sg-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: security
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # VPCエンドポイント用セキュリティグループ
  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for VPC Endpoints
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref CosignerSecurityGroup
          Description: "HTTPS from Cosigner"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref ECSSecurityGroup
          Description: "HTTPS from ECS"
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-vpc-endpoint-sg-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: security
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # ECS用セキュリティグループ
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS Fargate
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: "HTTP from ALB"
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationSecurityGroupId: !Ref VPCEndpointSecurityGroup
          Description: "HTTPS to VPC Endpoints"
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-ecs-sg-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: security
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # S3 Gateway Endpoint
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      VpcEndpointType: Gateway
      RouteTableIds:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateRouteTable-ID

  # SSM Interface Endpoint
  SSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssm"
      VpcEndpointType: Interface
      SubnetIds:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateSubnet-ID
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "ssm:*"
            Resource: "*"

  # SSM Messages Endpoint
  SSMMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssmmessages"
      VpcEndpointType: Interface
      SubnetIds:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateSubnet-ID
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # EC2 Messages Endpoint
  EC2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ec2messages"
      VpcEndpointType: Interface
      SubnetIds:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateSubnet-ID
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # ECR VPC Endpoint
  ECREndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.dkr"
      VpcEndpointType: Interface
      SubnetIds:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateSubnet-ID
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # CloudWatch Logs VPC Endpoint
  CloudWatchLogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      VpcEndpointType: Interface
      SubnetIds:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateSubnet-ID
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # Cosigner IAM Role
  CosignerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-cosigner-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: CosignerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/fireblocks-callback-infrastructure/*"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource: !GetAtt CosignerKMSKey.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ec2/cosigner*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub "arn:aws:s3:::${ProjectName}-cosigner-${Environment}-${AWS::AccountId}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource: !Sub "arn:aws:s3:::${ProjectName}-cosigner-${Environment}-${AWS::AccountId}"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: security
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # Cosigner Instance Profile
  CosignerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref CosignerRole

  # ECS Task Execution Role
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-ecs-task-execution-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ECSTaskExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/fireblocks-callback-infrastructure/*"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: security
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # ECS Task Role
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-ecs-task-role-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSTaskPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/fireblocks-callback-infrastructure/*"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: security
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # KMS Customer Managed Key for Cosigner
  CosignerKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "KMS key for Fireblocks Cosigner encryption"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Allow use of the key by Cosigner
            Effect: Allow
            Principal:
              AWS: !GetAtt CosignerRole.Arn
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
          - Sid: Allow use of the key by ECS Task
            Effect: Allow
            Principal:
              AWS: !GetAtt ECSTaskRole.Arn
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: security
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # KMS Key Alias for easier reference
  CosignerKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${ProjectName}-cosigner-${Environment}"
      TargetKeyId: !Ref CosignerKMSKey

Outputs:
  CosignerSecurityGroupId:
    Description: Cosigner Security Group ID
    Value: !Ref CosignerSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-CosignerSecurityGroup-ID

  ALBSecurityGroupId:
    Description: ALB Security Group ID
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ALBSecurityGroup-ID

  ECSSecurityGroupId:
    Description: ECS Security Group ID
    Value: !Ref ECSSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ECSSecurityGroup-ID

  VPCEndpointSecurityGroupId:
    Description: VPC Endpoint Security Group ID
    Value: !Ref VPCEndpointSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-VPCEndpointSecurityGroup-ID

  CosignerRoleArn:
    Description: Cosigner IAM Role ARN
    Value: !GetAtt CosignerRole.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-CosignerRole-ARN

  CosignerInstanceProfileArn:
    Description: Cosigner Instance Profile ARN
    Value: !GetAtt CosignerInstanceProfile.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-CosignerInstanceProfile-ARN

  ECSTaskExecutionRoleArn:
    Description: ECS Task Execution Role ARN
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ECSTaskExecutionRole-ARN

  ECSTaskRoleArn:
    Description: ECS Task Role ARN
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ECSTaskRole-ARN

  CosignerKMSKeyId:
    Description: Cosigner KMS Key ID
    Value: !Ref CosignerKMSKey
    Export:
      Name: !Sub ${ProjectName}-${Environment}-CosignerKMSKey-ID

  CosignerKMSKeyArn:
    Description: Cosigner KMS Key ARN
    Value: !GetAtt CosignerKMSKey.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-CosignerKMSKey-ARN
