AWSTemplateFormatVersion: "2010-09-09"
Description: "Fireblocks Callback Handler - Callback Handler Stack (ALB, ECS Fargate)"

Parameters:
  ProjectName:
    Type: String
    Default: fireblocks-cbh
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prod]
    Description: Environment name

  ContainerImage:
    Type: String
    Description: ECR image URI for callback handler
    Default: "nginx:latest" # プレースホルダー

  SSLCertificateArn:
    Type: String
    Description: SSL certificate ARN for ALB (will be created manually)

Resources:
  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/ecs/${ProjectName}-callback-handler-${Environment}"
      RetentionInDays: 30

  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ProjectName}-ecs-cluster-${Environment}
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-ecs-cluster-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: callback-handler
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # ECS Task Definition
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ProjectName}-ecs-task-${Environment}
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-ECSTaskExecutionRole-ARN
      TaskRoleArn:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-ECSTaskRole-ARN
      ContainerDefinitions:
        - Name: callback-handler
          Image: !Ref ContainerImage
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: LOG_LEVEL
              Value: info
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:3000/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: callback-handler
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-alb-${Environment}
      Type: application
      Scheme: internal
      IpAddressType: ipv4
      Subnets:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateSubnetA-ID
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateSubnetB-ID
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-ALBSecurityGroup-ID
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-alb-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: callback-handler
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-tg-${Environment}
      Port: 3000
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC-ID
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-tg-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: callback-handler
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # ALB Listener
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      Certificates:
        - CertificateArn: !Ref SSLCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # DNS Record for ALB
  ALBDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateHostedZone-ID
      Name:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
        EvaluateTargetHealth: true
      Comment: "A record pointing to ALB for callback handler"

  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ALBListener
    Properties:
      ServiceName: !Sub ${ProjectName}-ecs-service-${Environment}
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-ECSSecurityGroup-ID
          Subnets:
            - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateSubnetA-ID
            - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-PrivateSubnetB-ID
          AssignPublicIp: DISABLED
      LoadBalancers:
        - ContainerName: callback-handler
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroup
      HealthCheckGracePeriodSeconds: 300
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-ecs-service-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: Stack
          Value: callback-handler
        - Key: Project
          Value: fireblocks-callback-handler
        - Key: ManagedBy
          Value: cloudformation

  # CloudWatch Alarms
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-callback-handler-high-cpu-${Environment}
      AlarmDescription: "High CPU utilization for callback handler"
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: !Ref ECSService
        - Name: ClusterName
          Value: !Ref ECSCluster
      TreatMissingData: notBreaching

  HighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-callback-handler-high-memory-${Environment}
      AlarmDescription: "High memory utilization for callback handler"
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: !Ref ECSService
        - Name: ClusterName
          Value: !Ref ECSCluster
      TreatMissingData: notBreaching

Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ECSCluster-Name

  ECSServiceName:
    Description: ECS Service Name
    Value: !Ref ECSService
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ECSService-Name

  ApplicationLoadBalancerDNS:
    Description: Application Load Balancer DNS Name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ALB-DNS

  ApplicationLoadBalancerArn:
    Description: Application Load Balancer ARN
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub ${ProjectName}-${Environment}-ALB-ARN

  CallbackHandlerURL:
    Description: Callback Handler URL
    Value: !Sub
      - https://${DomainName}
      - DomainName:
          Fn::ImportValue: !Sub ${ProjectName}-${Environment}-DomainName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-CallbackHandler-URL
